### ISSUE TITLE
Error when importing faster_eval_coco in python3.7.5

### ISSUE THREAD

**Issue by Mark-ZhouWX** [MiXaiLL76/faster_coco_eval#9]
I am working with python3.7.5
```
Python 3.7.5
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

I got an error when import faster_eval_coco,
```
>>> import faster_coco_eval
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/MY_PYTHONPATH/lib/python3.7/site-packages/faster_coco_eval/__init__.py", line 1, in <module>
    from .core.faster_eval_api import COCOeval_faster
  File "/MY_PYTHONPATH/lib/python3.7/site-packages/faster_coco_eval/core/faster_eval_api.py", line 9, in <module>
    from .cocoeval import COCOeval
  File "<fstring>", line 1
    (iouType=)
            ^
```

Add I reproduce the error when I try
```
>>> print(f"{math.pi=}")
  File "<fstring>", line 1
    (math.pi=)
            ^
SyntaxError: invalid syntax

>>> print(f"{math.pi}")
3.141592653589793
```
It seem python 3.7 does not support this kind of f-string f"{math.pi=}", Do you have plan to fix this issue?

@MiXaiLL76

**Comment by MiXaiLL76** [comment]
fix in new version
